
export const DOMAIN = "http://localhost:3001/excel/";

export const LIMIT = 5;


export const HTTP_READ = "GET"
export const HTTP_CREATE = "POST"
export const HTTP_UPDATE = "PUT"
export const HTTP_DELETE = "DELETE"


export const HTTP_HEADER_JSON = {"Content-Type": "Application/json"}

export const GET_EXCEL_REQUEST = "GET_EXCEL_REQUEST"
export const GET_EXCEL_SUCCESS = "GET_EXCEL_SUCCESS"
export const GET_EXCEL_FAILURE = "GET_EXCEL_FAILURE"


export const ADD_EXCEL_REQUEST = "ADD_EXCEL_REQUEST"
export const ADD_EXCEL_SUCCESS = "ADD_EXCEL_SUCCESS"
export const ADD_EXCEL_FAILURE = "ADD_EXCEL_FAILURE"


export const DELETE_EXCEL_REQUEST = "DELETE_EXCEL_REQUEST"
export const DELETE_EXCEL_SUCCESS = "DELETE_EXCEL_SUCCESS"
export const DELETE_EXCEL_FAILURE = "DELETE_EXCEL_FAILURE"


export const UPDATE_EXCEL_REQUEST = "UPDATE_EXCEL_REQUEST"
export const UPDATE_EXCEL_SUCCESS = "UPDATE_EXCEL_SUCCESS"
export const UPDATE_EXCEL_FAILURE = "UPDATE_EXCEL_FAILURE"

export const UPLOAD_EXCEL_REQUEST = "UPLOAD_EXCEL_REQUEST"
export const UPLOAD_EXCEL_SUCCESS = "UPLOAD_EXCEL_SUCCESS"
export const UPLOAD_EXCEL_FAILURE = "UPLOAD_EXCEL_FAILURE"

